apiVersion: v1
kind: Service
metadata:
  name: nginx-svc    
  labels:
    app: nginx
spec:
  type: NodePort    
  ports:
  - port: 8080
    nodePort: 31472
    targetPort: 80
  selector:
    app: nginx
