apiVersion: v1
kind: Pod
metadata:
  name: pod-with-cpu-range
spec:
  containers:
  - name: pod-with-cpu-range
    image: nginx
    resources:
      limits:
        cpu: "800m"
      requests:
        cpu: "500m"
